version: '3.4'

services:
  retrogamingwebapi:
    image: ${DOCKER_REGISTRY-}retrogamingwebapi
    build:
      context: .
      dockerfile: RetroGamingWebAPI/Dockerfile

  healthcheckui:
    image: xabarilcoding/healthchecksui:latest
    environment:
      - HealthChecksUI:HealthChecks:0:Name=Readiness checks
      - HealthChecksUI:HealthChecks:0:Uri=http://retrogamingwebapi:8080/health/ready
      - HealthChecksUI:HealthChecks:1:Name=Liveliness checks
      - HealthChecksUI:HealthChecks:1:Uri=http://retrogamingwebapi:8080/health/lively
    ports:
      - 5000:80
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091
    labels:
      org.label-schema.group: "monitoring"

  maildev:
    container_name: "smtpserver"
    image: "maildev/maildev:2.0.5" # https://hub.docker.com/r/maildev/maildev
    ports:
      - "1025"
      - "1080:1080"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_SMTP_HOST=maildev:1025
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=alert@retrogamingwebapi.com
      - GF_SMTP_SKIP_VERIFY=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=azure_blob
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_NAME=retrogaming2048storage
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_KEY=b9U8Mnak7GwnWbRT3PWTrec3cf3AI5sEW9CBKXJ3uZ477cbCeqBPXr4b9kXPoUtBy71IcUfmDiee+AStoY8IOA==
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_CONTAINER_NAME=grafananotifications
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
    - 8081

volumes:
  grafana-storage: