version: '3.4'

services:
  retrogamingwebapi:
    image: ${DOCKER_REGISTRY-}retrogamingwebapi
    build:
      context: .
      dockerfile: RetroGamingWebAPI/Dockerfile

  healthcheckui:
    image: xabarilcoding/healthchecksui:latest
    environment:
      - HealthChecksUI:HealthChecks:0:Name=Readiness checks
      - HealthChecksUI:HealthChecks:0:Uri=http://retrogamingwebapi:8080/health/ready
      - HealthChecksUI:HealthChecks:1:Name=Liveliness checks
      - HealthChecksUI:HealthChecks:1:Uri=http://retrogamingwebapi:8080/health/lively
    ports:
      - 5000:80

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  maildev:
    image: "maildev/maildev:2.0.5" # https://hub.docker.com/r/maildev/maildev
    ports:
      - "1025"
      - "1080:1080"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_SMTP_HOST=maildev:1025
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=alert@retrogamingwebapi.com
      - GF_SMTP_SKIP_VERIFY=true

    depends_on:
      - prometheus
    ports:
      - 3000:3000

  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
    - 8081

volumes:
  grafana-storage: