version: '3.4'

services:
  retrogamingwebapi:
    image: ${DOCKER_REGISTRY-}retrogamingwebapi
    build:
      context: .
      dockerfile: RetroGamingWebAPI/Dockerfile

  healthcheckui:
    image: xabarilcoding/healthchecksui:latest
    environment:
      - HealthChecksUI:HealthChecks:0:Name=Readiness checks
      - HealthChecksUI:HealthChecks:0:Uri=http://retrogamingwebapi/health/ready
      - HealthChecksUI:HealthChecks:1:Name=Liveliness checks
      - HealthChecksUI:HealthChecks:1:Uri=http://retrogamingwebapi/health/lively
    ports:
      - 5000:80
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    ports:
      - 9091:9091
    labels:
      org.label-schema.group: "monitoring"

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100

  grafana:
    image: grafana/grafana
    volumes:
      - type: volume
        source: grafana-storage
        target: /var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=pass
      - GF_SMTP_HOST=localhost:25
      - GF_SMTP_ENABLED=true
      - GF_SMTP_FROM_ADDRESS=alert@retrogamingwebapi.com
      - GF_SMTP_SKIP_VERIFY=true
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=azure_blob
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_NAME=grafanaslacknotification
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_ACCOUNT_KEY=C3SLdvQAe+gXxho0dg1DVsbi3KdzDM1YFCD4fUbX7HS3oKOfpCO02ejKUk5Og5y611PdG6qCTiXb4HsUGNlqCQ==
      - GF_EXTERNAL_IMAGE_STORAGE_AZURE_BLOB_CONTAINER_NAME=alerts
    depends_on:
      - prometheus
    ports:
      - 3000:3000

volumes:
  grafana-storage: