apiVersion: "aspnetcore.ui/v1"
kind: HealthCheck
metadata:
  name: healthchecks-ui
  namespace: monitoringdemo
spec:
  name: healthchecks-ui
  scope: Namespaced #The UI will be created at specified namespace (demo) and will watch healthchecks services in demo namespace only
  #scope: Cluster The UI will be created at specified namespace (demo) but will watch healthcheck services across all namespaces
  servicesLabel: HealthChecks
  
  portNumber: 8180
  serviceType: LoadBalancer
  stylesheetContent: >
    :root {    
      --primaryColor: #2a3950;
      --secondaryColor: #f4f4f4;  
      --bgMenuActive: #e1b015;
      --bgButton: #e1b015;
      --logoImageUrl: url('https://vslive.com/~/media/ECG/VSLive/2022/austin/design/infobox.ashx');
      --bgAside: var(--primaryColor);   
    }
  #serviceAnnotations:
  #  - name: service.beta.kubernetes.io/azure-load-balancer-internal
  #    value: "true"
