# prometheus.yml
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'my-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'aspnetcorewebapi'
    scrape_interval: 5s
    metrics_path: /healthmetrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['host.docker.internal:443']